events {}

http {
    server {
        listen 8080;
        listen [::]:8080;

        server_name _;

        location /devnet {
            proxy_pass http://127.0.0.1:101;

            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location /xhttp {
            proxy_pass http://127.0.0.1:100;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            client_max_body_size 0;
            proxy_buffering off;
            proxy_request_buffering off;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location / {
            return 200 "OK\n";
        }
    }
}
